name: Build and Deploy Transcoder Service

on:
  push:
    branches: [main]
    paths:
      - "transcoder-service/**"
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-transcoder:
    name: Build Transcoder Service
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Transcoder
        uses: docker/build-push-action@v5
        with:
          context: ./transcoder-service
          file: ./transcoder-service/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/streamlet-transcoder-service:latest
            ${{ env.DOCKER_USERNAME }}/streamlet-transcoder-service:${{ env.SHORT_SHA }}

  deploy-transcoder:
    name: Deploy Transcoder Service
    runs-on: ubuntu-latest
    needs: build-transcoder
    environment: production
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_TRANSCODER }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY_TRANSCODER }}" \
          -H "Accept: application/json" \
          -d ''
